const icon=()=>window.lucide&&lucide.createIcons();
// Support the friendly country query used by the homepage quick-filter buttons.
const initialQuery=new URLSearchParams(location.search);if(initialQuery.has('country')&&!initialQuery.has('region')){initialQuery.set('region',initialQuery.get('country'));initialQuery.delete('country');history.replaceState(null,'',`${location.pathname}?${initialQuery.toString()}`)}
// Use stable cover images when a supplied photo URL is unavailable.
const imageOverrides={2:'https://lecerp.ug.edu.gh/sites/lecerp.ug.edu.gh/files/2025-05/Land_DJI_0101.jpg',3:'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=1200&q=85',13:'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=85'};
// Prefer authentic campus photographs from Wikimedia Commons as cards come into view.
const campusImageCache={};
async function resolveCampusImage(image){if(image.dataset.campusResolved)return;image.dataset.campusResolved='true';const university=universities.find(item=>item.name===image.alt);if(!university)return;try{const query=encodeURIComponent(`${university.name} campus`);const response=await fetch(`https://commons.wikimedia.org/w/api.php?origin=*&action=query&generator=search&gsrsearch=${query}&gsrnamespace=6&prop=imageinfo&iiprop=url&iiurlwidth=1000&format=json`);const data=await response.json();const page=Object.values(data.query?.pages||{})[0];const photo=page?.imageinfo?.[0]?.thumburl;if(photo){campusImageCache[university.id]=photo;image.src=photo}}catch(error){/* Existing cover image remains as a reliable fallback. */}}
function enableCampusPhotos(){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){resolveCampusImage(entry.target);observer.unobserve(entry.target)}}),{rootMargin:'180px'});document.querySelectorAll('.card-cover,.detail-cover').forEach(image=>{if(!image.dataset.campusObserver){image.dataset.campusObserver='true';observer.observe(image)}})}
function addCourseCatalogueLink(){const universityId=Number(new URLSearchParams(location.search).get('id'));const university=universities.find(item=>item.id===universityId);const factsBox=document.querySelector('.detail-side .side-box');if(!university||!factsBox||factsBox.querySelector('.catalogue-link'))return;const catalogueUrl=`https://www.google.com/search?q=${encodeURIComponent(university.name+' official course catalogue programmes')}`;factsBox.insertAdjacentHTML('beforeend',`<a class="catalogue-link" href="${catalogueUrl}" target="_blank" rel="noopener"><i data-lucide="book-open"></i> View full course catalogue <i data-lucide="external-link"></i></a>`);icon()}
universities.forEach(university=>{if(imageOverrides[university.id])university.coverImage=imageOverrides[university.id]});
// Preserve verified direct websites; give every remaining catalogue record a usable official-site lookup.
universities.forEach(university=>{if(!university.website||university.website==='#'){university.website=`https://www.google.com/search?q=${encodeURIComponent(university.name+' official website')}`;university.websiteLabel='Find official website'}else university.websiteLabel='Visit official website'});
const refreshPaymentContact=()=>document.querySelectorAll('.payment-contact').forEach(link=>{if(link.href.includes('tel:+233504238074')){link.href='tel:+233256344918';link.innerHTML='<i data-lucide="phone-call"></i> +233 256 344 918'}if(link.href.includes('wa.me/233256344918')){link.href='https://wa.me/233504238074?text=Hello%20CampusScope%2C%20I%20would%20like%20to%20complete%20my%20university%20application.';link.innerHTML='<i data-lucide="message-circle"></i> WhatsApp: +233 504 238 074'}});
new MutationObserver(refreshPaymentContact).observe(document.documentElement,{childList:true,subtree:true});
new MutationObserver(()=>document.querySelectorAll('a.btn[href*="google.com/search"]').forEach(link=>{if(!link.dataset.officialLookup){link.dataset.officialLookup='true';link.innerHTML='Find official website <i data-lucide="external-link"></i>';icon()}})).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('DOMContentLoaded',()=>{document.title=document.title.replace('UniFinder','CampusScope.com');document.querySelectorAll('.brand').forEach(brand=>brand.innerHTML='CampusScope<span>.com</span>')});
document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('.quick-filters a').forEach(link=>link.href=link.href.replace('?region=','?country=')));
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('footer').forEach(footer=>footer.insertAdjacentHTML('beforeend','<a class="customer-care" href="mailto:campusscope00@gmail.com"><i data-lucide="headphones"></i> Customer care: campusscope00@gmail.com</a>'));enableCampusPhotos();icon()});
new MutationObserver(enableCampusPhotos).observe(document.documentElement,{childList:true,subtree:true});
new MutationObserver(addCourseCatalogueLink).observe(document.documentElement,{childList:true,subtree:true});
// Inquiry applications lead students to a secure, direct payment-contact choice.
document.addEventListener('submit',event=>{const form=event.target;if(!form.matches('.inquiry'))return;event.preventDefault();event.stopImmediatePropagation();form.closest('.side-box').innerHTML=`<h3>Application request received</h3><div class="payment-note"><i data-lucide="circle-check-big"></i><p>Thank you. To complete your application and payment, contact our admissions support team.</p><strong>Choose a contact option:</strong><a class="payment-contact" href="tel:+233504238074"><i data-lucide="phone-call"></i> +233 504 238 074</a><a class="payment-contact whatsapp" target="_blank" href="https://wa.me/233256344918?text=Hello%20UniFinder%2C%20I%20would%20like%20to%20complete%20my%20university%20application."><i data-lucide="message-circle"></i> WhatsApp: +233 256 344 918</a><small>Please contact us before making any payment.</small></div>`;icon()},true);
document.addEventListener('error',event=>{const image=event.target;if(image.tagName==='IMG'&&!image.dataset.fallback){image.dataset.fallback='true';image.src='https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80'}},true);
function card(u){return `<a class="university-card" href="university.html?id=${u.id}"><img class="card-cover" src="${u.coverImage}" alt="${u.name}"><div class="card-body"><div class="card-meta"><span class="tag">${u.region}</span><span>Rank #${u.ranking}</span></div><h3>${u.name}</h3><span class="location"><i data-lucide="map-pin"></i>${u.location}</span><div class="card-bottom"><span>From <b>${u.currency} ${u.tuitionMin.toLocaleString()}</b>/yr</span><span>${u.type}</span></div></div></a>`}
function displayCards(list,target){target.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No universities match those filters. Try broadening your search.</div>';icon()}
function initBrowse(){const grid=document.querySelector('#university-grid');if(!grid)return;const search=document.querySelector('#university-search'),course=document.querySelector('#course-filter'),level=document.querySelector('#level-filter'),sort=document.querySelector('#sort-filter'),range=document.querySelector('#tuition-range'),rangeText=document.querySelector('#range-value'),checks=[...document.querySelectorAll('[name=country]')];let params=new URLSearchParams(location.search);search.value=params.get('q')||'';let region=params.get('region')||'';function render(){let list=universities.filter(u=>{let q=search.value.toLowerCase(),countries=checks.filter(c=>c.checked).map(c=>c.value);return (!q||u.name.toLowerCase().includes(q)||u.courses.join(' ').toLowerCase().includes(q))&&(!region||u.region===region)&&(!countries.length||countries.includes(u.region))&&(!course.value||u.courses.includes(course.value))&&(!level.value||u.level.includes(level.value))&&u.tuitionMin<=+range.value});if(sort.value==='tuition')list.sort((a,b)=>a.tuitionMin-b.tuitionMin);else list.sort((a,b)=>a.ranking-b.ranking);displayCards(list,grid)}[search,course,level,sort,range,...checks].forEach(e=>e.addEventListener('input',render));range.addEventListener('input',()=>rangeText.textContent=`Up to ${range.value>=70000?'70,000+':Number(range.value).toLocaleString()} USD`);render()}
function initDetail(){const root=document.querySelector('#university-detail');if(!root)return;let u=universities.find(x=>x.id===+new URLSearchParams(location.search).get('id'))||universities[0];document.title=`${u.name} | UniFinder`;root.innerHTML=`<div class="detail-main"><img class="detail-cover" src="${u.coverImage}" alt="${u.name}"><div class="detail-content"><div class="uni-title-row"><div><p class="eyebrow">${u.region.toUpperCase()} • ${u.type.toUpperCase()}</p><h1>${u.name}</h1><span class="location"><i data-lucide="map-pin"></i>${u.location}</span></div><span class="tag">#${u.ranking}</span></div><h2>About the university</h2><p>${u.about}</p><h2>Popular courses</h2><div class="pills">${u.courses.map(x=>`<span class="pill">${x}</span>`).join('')}</div><h2>Admission requirements</h2><p>${u.requirements}</p><h2>Scholarships</h2><div class="pills">${u.scholarships.map(x=>`<span class="pill">${x}</span>`).join('')}</div><h2>Location</h2><iframe class="map" loading="lazy" src="https://www.google.com/maps?q=${encodeURIComponent(u.location)}&output=embed"></iframe></div></div><aside class="detail-side"><div class="side-box"><h3>Quick facts</h3><div class="facts"><div class="fact"><i data-lucide="calendar"></i><span><b>Application deadline</b><br>${u.deadline}</span></div><div class="fact"><i data-lucide="graduation-cap"></i><span><b>Acceptance rate</b><br>${u.acceptanceRate}</span></div><div class="fact"><i data-lucide="wallet"></i><span><b>Tuition range</b><br>${u.currency} ${u.tuitionMin.toLocaleString()}–${u.tuitionMax.toLocaleString()}/yr</span></div></div><a class="btn" style="margin-top:20px;width:100%;justify-content:center" href="${u.website}" target="_blank">Official website <i data-lucide="external-link"></i></a></div><div class="side-box"><h3>Send an inquiry</h3><form class="inquiry"><input required placeholder="Full name"><input required type="email" placeholder="Email address"><input placeholder="Your country"><select><option>Course interested in</option>${u.courses.map(x=>`<option>${x}</option>`).join('')}</select><textarea placeholder="Tell us how we can help"></textarea><button class="btn">Send inquiry <i data-lucide="send"></i></button></form></div></aside>`;root.querySelector('.inquiry').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.insertAdjacentHTML('beforebegin','<div class="success">Thank you! Your inquiry has been received.</div>');e.currentTarget.reset();});icon()}
document.addEventListener('DOMContentLoaded',()=>{let f=document.querySelector('#featured-grid');if(f)displayCards(universities.slice(0,6),f);initBrowse();initDetail();document.querySelector('.menu-btn')?.addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));document.querySelectorAll('.contact-form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();f.innerHTML='<div class="success">Thank you! We will be in touch soon.</div>'}));icon()});
